server:
  port: 8080
  
spring:
  application:
    name: SPRING_API_GATEWAY

  cloud:
    gateway:
      routes:
      - id: Book-Service
        uri:
          lb://Book-Service
        predicates:
        - Path=/api/book/**
        
      - id: Customer-Service
        uri:
          lb://Customer-Service
        predicates:
        - Path=/api/customer**
        
      - id: Transaction-Service
        uri:
          lb://Transaction-Service
        predicates:
        - Path=/api/transaction**